name: Merge develop to release/vX.X
on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release branch to merge develop'     
        required: true
        default: 'release/v1.0'
  schedule:
  - cron: '*/5 * * * *'
jobs:
  merge-develop-to-release:
    runs-on: [ ubuntu-latest ] 
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge develop to release branch
      env:
        SOURCE_BRANCH: 'develop'
      run: |
          git fetch --unshallow
          git checkout ${{ env.SOURCE_BRANCH }}
          git pull
          git checkout ${{ github.event.inputs.releaseBranch || 'release/v1.0' }}
          git merge --no-ff ${{ env.SOURCE_BRANCH }}
          git push
