name: Image promotion
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version:'
        required: true
      service:
        type: choice
        description: 'Select service to promote:'     
        required: true
        options:
          - svc-1
          - svc-2
jobs:
  image-promotion:
    runs-on: [ ubuntu-latest ] 
    container: quay.io/skopeo/stable:v1.9.2
    steps:
    - name: Skopeo Promotion
      env:
        HARBOR_ROBOT_ACCOUNT: ${{ secrets.HARBOR_ROBOT_ACCOUNT }}
        run: |
          echo "Hello world"
        